#define TOOL_PANEL_TERRAIN_EDIT 500
#define TOOL_PANEL_TERRAIN_TEXTURE 501
#define TOOL_PANEL_TERRAIN_HEIGHT 502
#define TOOL_PANEL_TERRAIN_SMOOTH 503

#define MENU_FILE_NEW_MAP 600
#define MENU_FILE_OPEN_MAP 601
#define MENU_FILE_SAVE_MAP 602

#define MENU_MAP_MAP_PROPERTIES 610


#define NEW_MAP_OK 505
#define NEW_MAP_CANCEL 506

#define MENU_WINDOW_SHOW_TOOL_PREFERENCES 510
#define MENU_WINDOW_SHOW_TERRAIN_INFO 511
#define MENU_WINDOW_SHOW_RESOURCE_BROWSER 512
#define MENU_WINDOW_SHOW_TERRAIN_TOOLBAR 520

#define MENU_EDIT_UNDO 521
#define MENU_EDIT_REDO 522

//Start these at 30 to allow growing room for the task menu
#define NEW_MAP_DIALOG_MAP_NAME_CONTROL 530
#define NEW_MAP_DIALOG_MAP_WIDTH_SPIN 531
#define NEW_MAP_DIALOG_MAP_HEIGHT_SPIN 532

#define NEW_MAP_DIALOG_TERRAIN_VERTEX_COUNT_BOX 533
#define NEW_MAP_DIALOG_TERRAIN_SIZE_SPIN 534
#define NEW_MAP_DIALOG_TERRAIN_HEIGHT_SPIN 535


//Terrain edit preferences start at 550
#define TERRAIN_EDIT_PREFERENCES_BRUSH_SIZE_SLIDER 550
#define TERRAIN_EDIT_PREFERENCES_BRUSH_SIZE_SPIN 551
#define TERRAIN_EDIT_PREFERENCES_BRUSH_FLOW_SLIDER 552
#define TERRAIN_EDIT_PREFERENCES_BRUSH_FLOW_SPIN 553

#define TERRAIN_SMOOTH_PREFERENCES_BRUSH_SIZE_SLIDER 554
#define TERRAIN_SMOOTH_PREFERENCES_BRUSH_SIZE_SPIN 555
#define TERRAIN_SMOOTH_PREFERENCES_BRUSH_FLOW_SLIDER 556
#define TERRAIN_SMOOTH_PREFERENCES_BRUSH_FLOW_SPIN 557


#define TERRAIN_TEXTURE_PREFERENCES_BRUSH_SIZE_SLIDER 560
#define TERRAIN_TEXTURE_PREFERENCES_BRUSH_SIZE_SPIN 561
#define TERRAIN_TEXTURE_PREFERENCES_BRUSH_FLOW_SLIDER 562
#define TERRAIN_TEXTURE_PREFERENCES_BRUSH_FLOW_SPIN 563

#define TERRAIN_TEXTURE_PREFERENCES_TEXTURE_FIRST 564
#define TERRAIN_TEXTURE_PREFERENCES_TEXTURE_SECOND 565
#define TERRAIN_TEXTURE_PREFERENCES_TEXTURE_THIRD 566
#define TERRAIN_TEXTURE_PREFERENCES_TEXTURE_FOURTH 567


#define TERRAIN_HEIGHT_PREFERENCES_BRUSH_SIZE_SLIDER 568
#define TERRAIN_HEIGHT_PREFERENCES_BRUSH_SIZE_SPIN 569

//Terrain info
#define TERRAIN_INFO_LAYER_CHECK_BOX 570
#define TERRAIN_INFO_LAYER_IMAGE_SELECT_BUTTON 571
#define TERRAIN_INFO_NEW_LAYER_BUTTON 572
#define TERRAIN_INFO_UP_LAYER_BUTTON 573
#define TERRAIN_INFO_DOWN_LAYER_BUTTON 574
#define TERRAIN_INFO_DELETE_LAYER_BUTTON 575

#define TERRAIN_INFO_REFRESH 576

#define MAP_PROPERTIES_DIALOG_RESOURCES_ADD 580
#define MAP_PROPERTIES_DIALOG_RESOURCES_EDIT 581
#define MAP_PROPERTIES_DIALOG_RESOURCES_DELETE 582

#define TERRAIN_LAYER_DIALOG_CANCEL 590
#define TERRAIN_LAYER_DIALOG_SELECT 591
